(in-ns 'lp4.main)

(defn catalogo [lista] (
	if (.exists (clojure.java.io/file "catalogo.txt"))
		(with-open [rdr (reader "catalogo.txt")]
			((def linhas (line-seq rdr))
				(while (not= linhas nil)
					((def categoria (first linhas))
						(def linhas (rest linhas))
						(def id (bigdec (first linhas)))
						(def linhas (rest linhas))
						(def owner (first linhas))
						(def linhas (rest linhas))
						(case categoria
							"casa" ()
							"apto" ()
							"trapez" ()
							"triang" ()
							"retang" ()
							(println "Categoria: " categoria)
						)
						(def linhas (rest (rest linhas)))
					)
				)
			)
		)
	(println "Catalogo nao encontrado.")
	)
	(lista)
)